### ISSUE TITLE
Missing Featured Images

### ISSUE THREAD

**Issue by michaeltieso** [reddcoin-project/website#3]
Any graphic designers out there that can help with the featured images on the homepage? We need one for Proof of Stake Velocity, Tip Platform, Redd-ID, and ReddWallet. Size I put as an example is 500x300 but happy to take suggestions.

**Comment by ErikThiart** [comment]
Hey, @michaeltieso do you still need help, pop me an email quickly, let's get this rolling. 
me at erikthiart.com

**Comment by michaeltieso** [comment]
@ErikThiart shoot me over an email at mdt@michaeltieso.com
