### ISSUE TITLE
Replace Reddcoin Colors Image

### ISSUE THREAD

**Issue by michaeltieso** [reddcoin-project/website#6]
https://github.com/reddcoin-project/website/blob/cd77d070c96d475cbc0549208c2b6165c822a7d4/brandassets.html#L13

Seen here: https://github.com/reddcoin-project/website/blob/master/assets/images/reddcoin-colors.png

![reddcoin-colors](https://user-images.githubusercontent.com/1500606/36850912-31add374-1d68-11e8-86b7-b8194e4efe7b.png)

It'd be good to replace this with text instead of an image. Seen on the brand page.

**Comment by garylocke** [comment]
Submitted a PR for this. See #8

**Comment by michaeltieso** [comment]
Fixed in #8
