### ISSUE TITLE
Update #FAFAFA Color

### ISSUE THREAD

**Issue by JimboReddJones** [reddcoin-project/website#9]
![afbeelding](https://user-images.githubusercontent.com/35225336/36894512-dfee131a-1e0b-11e8-954a-053dbc8b577a.png)

**Comment by JimboReddJones** [comment]
Kai requested this in a PM

**Comment by michaeltieso** [comment]
Thanks for submitting. I'll take care of this. To clarify, #FAFAFA is missing as a background color in the download section. Fonts are set as #FAFAFA already. If there are any other sections that require #FAFAFA that I may have missed, please provide additional details. Thanks.
